# https://github.com/rust-rocksdb/rust-rocksdb/issues/535

[build]
target = "x86_64-unknown-linux-gnu"

[target.x86_64-unknown-linux-gnu]
rustflags = [
  "-C", "link-arg=-Wl,--allow-multiple-definition"
]

[target.aarch64-unknown-linux-gnu]
rustflags = [
  "-C", "link-arg=-Wl,--allow-multiple-definition"
]
